### ISSUE TITLE
Calling xgetres from within scripts

### ISSUE THREAD

**Issue by kgilmer** [tamirzb/xgetres#2]
Hello!  I want to embed xgetres calls from within scripts.  The program adds a linefeed when printing the value which is not ideal for this usecase.  I'm not aware of a way around this other than modifying the program to not print the linefeed.  Am I missing anything?

**Comment by kgilmer** [comment]
I ended up creating [my own version](https://github.com/regolith-linux/xrescat) that does this and also allows the specification of a default value in case the xresource is undefined.

**Comment by tamirzb** [comment]
Hey, sorry for the delay, only seen this now.

I guess you already solved it for your usecase, but out of interest, how does the linefeed interfere with scripting? I have used this in my own bash scripts without any issues. AFAIK adding a linefeed is kind of the standard for command line utilities. `cat` is a bit special as it outputs raw data of files, and as files can contain linefeeds adding an extra one at the end would be confusing. Other than `cat` I can't actually think of any other command line utility right now which doesn't add a linefeed, the vast majority of them definitely do.

**Comment by kgilmer** [comment]
Hi @tamirzb !  I am using a version of xgetres (without linefeeds and the extra ability to specify a default if a value does not exist in Xresources) in scripts such as i3blocks blocklets.  In cases I am extracting values from Xresources to embed them into Pango markup definitions, like this:
```
#!/bin/sh
DATE_FORMAT=`xrescat i3xrocks.date.format "+ %m-%d %H:%M "`
echo "<span font_desc='`xrescat i3xrocks.value.font`' color='`xrescat i3xrocks.value.font`'>`date "$DATE_FORMAT"`</span>"
```

The linefeeds to do not work with Pango in my experience.  In my case, I do not really use my version of xgetrex (I called it xrescat) on the command-line manually, but rather embed them in scripts to execute via the `` operators.

If you agree this functionality is of value generally and you'd like to take the functionality into xgetres I can prepare a PR, or if you'd prefer to keep xgetres as-is I totally understand.  Thanks again for your program and attention!

**Comment by tamirzb** [comment]
Yeah, I'm not sure how the linefeed interferes with this usage. `` expects a newline and therefore omits it.

Here's a script to demonstrate it:
```bash
#!/bin/sh
echo "xgetres dpi is `xgetres Xft.dpi` and it doesn't add a newline"
XRESCAT_DPI=`xrescat Xft.dpi`
XGETRES_DPI=`xgetres Xft.dpi`
echo -n "xgetres and xrescat are "
if [ "$XRESCAT_DPI" = "$XGETRES_DPI" ]; then
    echo "equal"
else
    echo "not equal"
fi
```
And the output I get is:
```
xgetres dpi is 96 and it doesn't add a newline
xgetres and xrescat are equal
```

**Comment by kgilmer** [comment]
You're right @tamirzb .  I'm guessing I was working on the command line and noticed the linefeed.  I was not aware of the "remove lf" property of ``.  But searching for this yields https://superuser.com/questions/403800/how-can-i-make-the-bash-backtick-operator-keep-newlines-in-output and yeah that settles it.  Interested in adding an optional second parameter as a default value?  :smile:

**Comment by tamirzb** [comment]
I like to keep things simple and I feel that this can be solved in other ways.

For instance, using bash you can do:
```bash
xgetres foo.bar || echo defaultvalue
```

**Comment by kgilmer** [comment]
Yeah, I understand your perspective.  For my usecase it's a bit nicer to have the default in-line, so I'll continue to use my version for now.  I may revert back to xgetres in the future.
